### ISSUE TITLE
HTTP error code

### ISSUE THREAD

**Issue by priore** [thibaultCha/TCBlobDownload#31]
Hi,
first, its a great job!

second, how i can solve for a 416 http when starting a download ?

tnks

**Comment by tarzon** [comment]
Hi @thibaultCha , I am also facing this issue. I my case there is nothing wrong with the url, but instead this error is only shown when the download is complete and you again tries to download the file.

` Download Stopped with error Error Domain=com.thibaultcha.tcblobdownload Code=1 "Erroneous HTTP status code 416 (requested range not satisfiable)" UserInfo=0x7fde59dac680 {NSLocalizedDescription=Erroneous HTTP status code 416 (requested range not satisfiable), TCBlobDownloadErrorHTTPStatusKey=416}
`

**Comment by thibaultCha** [comment]
Hi,

Can you describe exactly how you got this issue? What I understand reading your comment is that the file was 100% downloaded, and it somehow tried to download the file again, is that it? Or is your code trying to download the file again? (Which would, indeed, probably results in throwing that error)

**Comment by tarzon** [comment]
Hi,
Yes the file was 100% downloaded, and after that when i tried to download it again, i got that error.

**Comment by thibaultCha** [comment]
That is expected. When the library detects a part of the file (bas on its name) has already been downloaded, it sets the HTTP `Range` header. Since the range header is here set to the last byte of the file, the server is basically saying there is nothing left to download, thus the range is not satisfiable.

I agree this might be misleading and somehow signalling the file has already been downloaded would be more intuitive. This is a non covered use case.

**Comment by tarzon** [comment]
Okey. Got it. 
Thanks :) 
Great Work :+1:

**Comment by mrjlovetian** [comment]
I have a question, in my use tcblobdownload ,i think pause download,but i
don't konw use;
also i am an chinese people , i use tcblobdownload don't use chinese
