### ISSUE TITLE
Swift Version

### ISSUE THREAD

**Issue by dimohamdy** [thibaultCha/TCBlobDownload#42]
We need Swift Version

**Comment by thibaultCha** [comment]
If you are still interested, I am currently developing [TCBlobDownloadSwift](https://github.com/thibaultCha/TCBlobDownloadSwift) which is using `NSURLSession` for iOS 7+.

Using `NSURLSession` was my primary motivation for this new version but since it is written in Swift, I thought you might be interested.

**Comment by dimohamdy** [comment]
really I am glad
