### ISSUE TITLE
Crash on calling [TCBlobDownloadManager sharedInstance]

### ISSUE THREAD

**Issue by tarzon** [thibaultCha/TCBlobDownload#47]
The crash was received as unrecognized selector setName sent to instance.
 `  [sharedManager setName:@"TCBlobDownloadManager_SharedInstance_Queue"];`

Commenting it worked like a charm. :+1:

**Comment by albertschulz** [comment]
Yes, seems like there is some code missing

**Comment by thibaultCha** [comment]
Daaaaamn damn objective-c ! Thanks and sorry about that haha. `setName` should be called on the underlaying `NSOperationQueue`. My bad. Will push a fix shortly.

**Comment by albertschulz** [comment]
For me they also crash at this point. Weird.

**Comment by thibaultCha** [comment]
Okay so this was fixed, along with a small refactor and some more tests, but now I discovered tests are failing because Travis switched to xctool, which apparently doesn't handle HTTP connections very well... (see facebook/xctool#451) :disappointed: 

So for now, tests will be failing until I find a way and also make them more robust. Also, I'd like to do a bunch of stuff before releasing `2.1.0` (which fix this by adding a new method) as described here: #48 

I'm going to reopen this issue in case somebody else is having troubles with this issue until `2.1.0` is out.

All this is keeping me from working on the new Swift, iOS 8 version I was implementing :sob:

**Comment by thibaultCha** [comment]
`2.1.0` here we are. Thanks for the report
