### ISSUE TITLE
Progress cannot recover when resume from previous task

### ISSUE THREAD

**Issue by fsjack** [thibaultCha/TCBlobDownload#51]
Hi,
I use TCBlobDownload in my project to download mp3 files.I stop the downloading when the progress goes to about 50% then restart the task.It still start at 0%, I have checked the code, it seem supports the resuming function but the progress do not recover?

**Comment by thibaultCha** [comment]
Hi,

As explained [here](https://github.com/thibaultCha/TCBlobDownload/issues/9#issuecomment-29448021), the `receivedLength` and `totalSize` properties refer to the current request. I did not implement progress recover because this went beyond the scope of the library for my usages. It could potentially be added by a few lines of code setting the already downloaded size in [this else](https://github.com/thibaultCha/TCBlobDownload/blob/master/TCBlobDownload/TCBlobDownload/TCBlobDownloader.m#L139).

Please consider TCBlobDownloadSwift perhaps? It supports iOS 7's `NSURLSession` and thus is much more powerful for downloads in recent applications. (And supports `cancelWithResumeData:`, `downloadFileWithResumeData:`, which wraps `downloadTaskWithResumeData`

**Comment by fsjack** [comment]
Thanks for your reply!
I have forked this project and add this feature.Hope there's no bug :)

**Comment by thibaultCha** [comment]
Fell free to submit a pull request.
