### ISSUE TITLE
iOS 10 - crash in start method

### ISSUE THREAD

**Issue by michalcichon** [thibaultCha/TCBlobDownload#72]
I experienced random crashes in start method in iOS 10:

`[runLoop run];`

Are this library supporting iOS 10? Are you planning iOS 10 update?

**Comment by thibaultcha** [comment]
Hi,

I wouldn't know the exact reason behind this but I would strongly consider using a different library for iOS 10 and beyond, as I am not maintaining this anymore. Maybe the Swift version would be a better fit, especially considering it uses the official iOS 7+ download APIs instead of manually implementing them.
